# Generated by Django 5.2.13 on 2026-08-31 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('est_yer', models.IntegerField()),
                ('origien', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.CharField(max_length=100)),
                ('engien_cc', models.CharField(max_length=100)),
                ('fuel_Type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('EV', 'ev')], max_length=100)),
                ('miliege', models.CharField(max_length=100)),
                ('settings', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='cbv.company')),
            ],
        ),
    ]
