# Generated by Django 5.2.13 on 2026-09-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='producets',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='productimage/'),
        ),
    ]
